### ISSUE TITLE
Define and implement the development pipelines

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/cloud-hosted-guide-converter#111]
Currently, there is only a main branch.  If any change for the converter code, it may break the conversion for the cloud-hosted guides production.

Need to define the development and deployment process:
- a dev or staging branch
- PR review and merge process
- how to verify the code on the dev/staging branch 
- what is the deployment flow

**Comment by jakub-pomykala** [comment]
There is already a PR checker implemented which runs Guide-getting-started and compares it to a file that is in this repository. I will be looking into connecting this repo with a cloud-hosted-guide so that we can check a guide on there. Another thing I would like to look into is using the action to run all guides in this repo. I would like to store all the guides in this repo and then that action would create a PR which will show the person making the changes to the guideConverter what exactly has changed.

**Comment by jakub-pomykala** [comment]
Dev branch has been created. Need to get Tom Evans to give permissions to @gkwan-ibm and @jamiecoleman92 so that they can control this repository.

**Comment by jakub-pomykala** [comment]
[Document with development process instructions](https://ibm.ent.box.com/file/782303759529)

**Comment by jakub-pomykala** [comment]
This issue can now be closed however, I think this action could be made better by opening just one PR instead of one per Guide. I think this is something that should be implemented in the future therefore I have opened a new issue with enhancement tag [here](https://github.com/OpenLiberty/cloud-hosted-guide-converter/issues/131)
