### ISSUE TITLE
Gilbert Prolems

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/cloud-hosted-guide-converter#123]
- [ ] the last step of the [cloud-hosted-guide-getting-started in staging SN](https://labs.cognitiveclass.ai/tools/theiadocker/lab/tree?md_instructions_url=https://cf-course-data-staging.s3.us-east.cloud-object-storage.appdomain.cloud/cloud-hosted-guide-getting-started/instructions.md) does not show subtitle `## Clean up your environment` but the [source](https://raw.githubusercontent.com/OpenLiberty/cloud-hosted-guides/staging/instructions/cloud-hosted-guide-getting-started/instructions.md) looks good
- [ ] the last 2 steps of the [cloud-hosted-guide-microprofile-config in staging SN](https://labs.cognitiveclass.ai/tools/theiadocker/lab/tree?md_instructions_url=https://cf-course-data-staging.s3.us-east.cloud-object-storage.appdomain.cloud/cloud-hosted-guide-microprofile-config/instructions.md) are not combined yet but the [source](https://raw.githubusercontent.com/OpenLiberty/cloud-hosted-guides/staging/instructions/cloud-hosted-guide-microprofile-config/instructions.md) looks good
- [ ] manual converted the guide-microprofile-config by action https://github.com/OpenLiberty/cloud-hosted-guides/actions/runs/624979269 but failed with unusual download `java.io.FileNotFoundException: https://raw.githubusercontent.com/openliberty/guide-microprofile-config-intro/master/README.adoc` at line 3366 from `Run Converter` step

**Comment by jakub-pomykala** [comment]
- [ ] [cloud-hosted-guide-getting-started-staging](https://labs.cognitiveclass.ai/tools/theiadocker/lab/tree?md_instructions_url=https://cf-course-data-staging.s3.us-east.cloud-object-storage.appdomain.cloud/cloud-hosted-guide-getting-started/instructions.md&lti=true) - `## Clean up your environment` subheading is there (screenshot bellow):


![Screenshot 2021-03-08 at 10 00 56](https://user-images.githubusercontent.com/56261244/110305947-2df9e900-7ff5-11eb-8fa8-c1b9b7683f95.png)

- [ ][ cloud-hosted-guide-microprofile-config-staging](https://labs.cognitiveclass.ai/tools/theiadocker/lab/tree?md_instructions_url=https://cf-course-data-staging.s3.us-east.cloud-object-storage.appdomain.cloud/cloud-hosted-guide-microprofile-config/instructions.md&lti=true) last two steps are together as seen in screenshot bellow:

![Screenshot 2021-03-08 at 10 01 58](https://user-images.githubusercontent.com/56261244/110306074-5386f280-7ff5-11eb-861f-6070535c7042.png)

- [ ] The action failed because there was nothing to commit. The error message was printed out because `guide-microprofile-config-intro` is an iGuide which does not have a readme.adoc file. This error needs to be ignored. I will add a function to the GuideConverter to do so.

**Comment by jakub-pomykala** [comment]
Linked PR is to give new output message for iGuides link function
